### ISSUE TITLE
layoutManager is StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by iddangunawan** [skydoves/BaseRecyclerViewAdapter#6]
**Is your feature request related to a problem?**
how to set layoutManager StaggeredGridLayoutManager ? i can't find val loadMode RecyclerViewPaginator triggered

**Describe the solution you'd like:**
-

**Describe alternatives you've considered:**
-

**Comment by skydoves** [comment]
Hi, It has been released a new version `1.0.4`!
Thanks for your issue :)
